import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Providers } from "app/redux/provider";
import Footer from "app/components/Footer/Footer";
import StyledComponentsRegistry from "./StyledComponentsRegistry";

const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "700","900"], });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
      <StyledComponentsRegistry>
        <Providers>
          {children}
          <Footer/>
        </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
